services:
  binderhub:
    tty: true
    image: sphanit/cohan-virtual-labs:noetic
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cohan-multiverse-binder-container
    command: jupyter lab --allow-root --no-browser --ip=0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''

    ports:
      - 8888:8888
