image: laas.pgm
resolution: 0.050000
origin: [-20.000000, -20.000000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

## For the simulator
speed: 2.0              # Keyboard linear speed (m/s)
angular_speed: 1.5708   # Keyboard angular speed (rad/s), default pi/2

entities:
  - name: robot
    start_x: 2
    start_y: 2
    start_theta: 0
    radius: 0.3
    color: [0, 100, 255, 255]
    use_keyboard: true
    use_differential: false
    use_laser: true
    laser_range: 7
    laser_resolution: 1081
    laser_angle: 4.71239
  - name: human1
    start_x: 8
    start_y: 2.1
    start_theta: 3.14
    radius: 0.3
    color: [150, 75, 0, 255]
    use_keyboard: false
    use_differential: false
    use_laser: true
    laser_range: 7
    laser_resolution: 1081
    laser_angle: 4.71239
  - name: human2
    start_x: 7.5
    start_y: 5.0
    start_theta: 1.57
    radius: 0.3
    color: [150, 75, 0, 255]
    use_keyboard: false
    use_differential: false
    use_laser: true
    laser_range: 7
    laser_resolution: 1081
    laser_angle: 4.71239
